// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// jaccard_fast_matrix
NumericMatrix jaccard_fast_matrix(NumericMatrix mat);
RcppExport SEXP _fastJaccard_jaccard_fast_matrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_fast_matrix(mat));
    return rcpp_result_gen;
END_RCPP
}
// parallelVectorSum
int parallelVectorSum(IntegerVector x);
RcppExport SEXP _fastJaccard_parallelVectorSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelVectorSum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastJaccard_jaccard_fast_matrix", (DL_FUNC) &_fastJaccard_jaccard_fast_matrix, 1},
    {"_fastJaccard_parallelVectorSum", (DL_FUNC) &_fastJaccard_parallelVectorSum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastJaccard(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
