# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get Jaccard simmilarity for matrix rows
#'
#' @param mat Binary m x n matrix to be evaluated
#' @return Jaccard m x m simmilarity matrix
jaccard_fast_matrix <- function(mat) {
    .Call(`_fastJaccard_jaccard_fast_matrix`, mat)
}

#' Parallel sum of a vector
#'
#' @param x Integer vector
#' @return integer sum of vector
parallelVectorSum <- function(x) {
    .Call(`_fastJaccard_parallelVectorSum`, x)
}

